#!/usr/bin/env bash
clear
while :
do
echo "  ▄           ▄  "
echo " ▐█           █▌ "
echo " ▌ █         █ ▐ "
echo "▐   █       █   ▌"
echo " ▌  ▄▄     ▄▄  ▐ "
echo "   ████   ████   "
echo "  ▐█▀  ▌ ▐  ▀█▌  "
echo "  ▐▌   ▌ ▐   ▐▌  "
echo "   ▀▄▄▀   ▀▄▄▀   "
echo "        │        "
echo "  ≥≡≡ └─┴─┘ ≡≡≤  "
sleep 3
clear
echo "  ▄           ▄  "
echo " ▐█           █▌ "
echo " ▌ █         █ ▐ "
echo "▐   █       █   ▌"
echo " ▌  ▄▄     ▄▄  ▐ "
echo "   ████   ████   "
echo "  ▐█▀▀▀▌ ▐▀▀▀█▌  "
echo "  ▐▌   ▌ ▐   ▐▌  "
echo "   ▀▄▄▀   ▀▄▄▀   "
echo "        │        "
echo "  ≥≡≡ └─┴─┘ ≡≡≤  "
sleep 0.01
clear
echo "  ▄           ▄  "
echo " ▐█           █▌ "
echo " ▌ █         █ ▐ "
echo "▐   █       █   ▌"
echo " ▌  ▄▄     ▄▄  ▐ "
echo "   ████   ████   "
echo "  ▐████▌ ▐████▌  "
echo "  ▐▌   ▌ ▐   ▐▌  "
echo "   ▀▄▄▀   ▀▄▄▀   "
echo "        │        "
echo "  ≥≡≡ └─┴─┘ ≡≡≤  "
sleep 0.01
clear
echo "  ▄           ▄  "
echo " ▐█           █▌ "
echo " ▌ █         █ ▐ "
echo "▐   █       █   ▌"
echo " ▌  ▄▄     ▄▄  ▐ "
echo "   ████   ████   "
echo "  ▐████▌ ▐████▌  "
echo "  ▐████▌ ▐████▌  "
echo "   ▀██▀   ▀██▀   "
echo "        │        "
echo "  ≥≡≡ └─┴─┘ ≡≡≤  "
sleep 0.01
clear
echo "  ▄           ▄  "
echo " ▐█           █▌ "
echo " ▌ █         █ ▐ "
echo "▐   █       █   ▌"
echo " ▌  ▄▄     ▄▄  ▐ "
echo "   ████   ████   "
echo "  ▐████▌ ▐████▌  "
echo "  ▐▌   ▌ ▐   ▐▌  "
echo "   ▀▄▄▀   ▀▄▄▀   "
echo "        │        "
echo "  ≥≡≡ └─┴─┘ ≡≡≤  "
sleep 0.01
clear
echo "  ▄           ▄  "
echo " ▐█           █▌ "
echo " ▌ █         █ ▐ "
echo "▐   █       █   ▌"
echo " ▌  ▄▄     ▄▄  ▐ "
echo "   ████   ████   "
echo "  ▐█▀▀▀▌ ▐▀▀▀█▌  "
echo "  ▐▌   ▌ ▐   ▐▌  "
echo "   ▀▄▄▀   ▀▄▄▀   "
echo "        │        "
echo "  ≥≡≡ └─┴─┘ ≡≡≤  "
sleep 0.01
clear
echo "  ▄           ▄  "
echo " ▐█           █▌ "
echo " ▌ █         █ ▐ "
echo "▐   █       █   ▌"
echo " ▌  ▄▄     ▄▄  ▐ "
echo "   ████   ████   "
echo "  ▐█▀  ▌ ▐  ▀█▌  "
echo "  ▐▌   ▌ ▐   ▐▌  "
echo "   ▀▄▄▀   ▀▄▄▀   "
echo "        │        "
echo "  ≥≡≡ └─┴─┘ ≡≡≤  "
sleep 0.01
clear
if  (( $RANDOM %3 == 0 ))
then
echo "  ▄           ▄  "
echo " ▐█           █▌ "
echo " ▌ █         █ ▐ "
echo "▐   █       █   ▌"
echo " ▌  ▄▄     ▄▄  ▐ "
echo "   ████   ████   "
echo "  ▐█▀▀▀▌ ▐▀▀▀█▌  "
echo "  ▐▌   ▌ ▐   ▐▌  "
echo "   ▀▄▄▀   ▀▄▄▀   "
echo "        │        "
echo "  ≥≡≡ └─┴─┘ ≡≡≤  "
sleep 0.01
clear
echo "  ▄           ▄  "
echo " ▐█           █▌ "
echo " ▌ █         █ ▐ "
echo "▐   █       █   ▌"
echo " ▌  ▄▄     ▄▄  ▐ "
echo "   ████   ████   "
echo "  ▐████▌ ▐████▌  "
echo "  ▐▌   ▌ ▐   ▐▌  "
echo "   ▀▄▄▀   ▀▄▄▀   "
echo "        │        "
echo "  ≥≡≡ └─┴─┘ ≡≡≤  "
sleep 0.01
clear
echo "  ▄           ▄  "
echo " ▐█           █▌ "
echo " ▌ █         █ ▐ "
echo "▐   █       █   ▌"
echo " ▌  ▄▄     ▄▄  ▐ "
echo "   ████   ████   "
echo "  ▐████▌ ▐████▌  "
echo "  ▐████▌ ▐████▌  "
echo "   ▀██▀   ▀██▀   "
echo "        │        "
echo "  ≥≡≡ └─┴─┘ ≡≡≤  "
sleep 0.01
clear
echo "  ▄           ▄  "
echo " ▐█           █▌ "
echo " ▌ █         █ ▐ "
echo "▐   █       █   ▌"
echo " ▌  ▄▄     ▄▄  ▐ "
echo "   ████   ████   "
echo "  ▐████▌ ▐████▌  "
echo "  ▐▌   ▌ ▐   ▐▌  "
echo "   ▀▄▄▀   ▀▄▄▀   "
echo "        │        "
echo "  ≥≡≡ └─┴─┘ ≡≡≤  "
sleep 0.01
clear
echo "  ▄           ▄  "
echo " ▐█           █▌ "
echo " ▌ █         █ ▐ "
echo "▐   █       █   ▌"
echo " ▌  ▄▄     ▄▄  ▐ "
echo "   ████   ████   "
echo "  ▐█▀▀▀▌ ▐▀▀▀█▌  "
echo "  ▐▌   ▌ ▐   ▐▌  "
echo "   ▀▄▄▀   ▀▄▄▀   "
echo "        │        "
echo "  ≥≡≡ └─┴─┘ ≡≡≤  "
sleep 0.01
clear
echo "  ▄           ▄  "
echo " ▐█           █▌ "
echo " ▌ █         █ ▐ "
echo "▐   █       █   ▌"
echo " ▌  ▄▄     ▄▄  ▐ "
echo "   ████   ████   "
echo "  ▐█▀▀▀▌ ▐▀▀▀█▌  "
echo "  ▐▌   ▌ ▐   ▐▌  "
echo "   ▀▄▄▀   ▀▄▄▀   "
echo "        │        "
echo "  ≥≡≡ └─┴─┘ ≡≡≤  "
sleep 0.01
clear
echo "  ▄           ▄  "
echo " ▐█           █▌ "
echo " ▌ █         █ ▐ "
echo "▐   █       █   ▌"
echo " ▌  ▄▄     ▄▄  ▐ "
echo "   ████   ████   "
echo "  ▐█▀  ▌ ▐  ▀█▌  "
echo "  ▐▌   ▌ ▐   ▐▌  "
echo "   ▀▄▄▀   ▀▄▄▀   "
echo "        │        "
echo "  ≥≡≡ └─┴─┘ ≡≡≤  "
sleep 5
clear
fi
if  (( $RANDOM %4 == 0 ))
then
echo "  ▄           ▄  "
echo " ▐█           █▌ "
echo " ▌ █         █ ▐ "
echo "▐   █       █   ▌"
echo " ▌  ▄▄     ▄▄  ▐ "
echo "   ████   ████   "
echo "  ▐█▀  ▌ ▐  ▀█▌  "
echo "  ▐▌   ▌ ▐   ▐▌  "
echo "   ▀▄▄▀   ▀▄▄▀   "
echo "        │        "
echo "  ≥≡≡ └─┴─┘ ≡≡≤  "
sleep 0.1
clear
fi
if  (( $RANDOM %2 == 0 ))
then
echo "  ▄           ▄  "
echo " ▐█           █▌ "
echo " ▌ █         █ ▐ "
echo "▐   █       █   ▌"
echo " ▌  ▄▄     ▄▄  ▐ "
echo "   ████   ████   "
echo "  ▐█▀  ▌ ▐  ▀█▌  "
echo "  ▐▌   ▌ ▐   ▐▌  "
echo "   ▀▄▄▀   ▀▄▄▀   "
echo "        │        "
echo "  ≥≡≡ └─┴─┘ ≡≡≤  "
sleep 6
clear
fi
if  (( $RANDOM %5 == 0 ))
then
echo "  ▄           ▄  "
echo " ▐█           █▌ "
echo " ▌ █         █ ▐ "
echo "▐   █       █   ▌"
echo " ▌  ▄▄     ▄▄  ▐ "
echo "   ████   ████   "
echo "  ▐█▀  ▌ ▐  ▀█▌  "
echo "  ▐▌   ▌ ▐   ▐▌  "
echo "   ▀▄▄▀   ▀▄▄▀   "
echo "        │        "
echo "  ≥≡≡ └─┴─┘ ≡≡≤  "
sleep 0.03
clear
echo "  ▄           ▄  "
echo " ▐█           █▌ "
echo " ▌ █         █ ▐ "
echo "▐   █       █   ▌"
echo " ▌  ▄▄     ▄▄  ▐ "
echo "   ████   ████   "
echo "  ▐█▀▀▀▌ ▐▀▀▀█▌  "
echo "  ▐▌   ▌ ▐   ▐▌  "
echo "   ▀▄▄▀   ▀▄▄▀   "
echo "        │        "
echo "  ≥≡≡ └─┴─┘ ≡≡≤  "
sleep 0.03
clear
echo "  ▄           ▄  "
echo " ▐█           █▌ "
echo " ▌ █         █ ▐ "
echo "▐   █       █   ▌"
echo " ▌  ▄▄     ▄▄  ▐ "
echo "   ████   ████   "
echo "  ▐████▌ ▐████▌  "
echo "  ▐▌   ▌ ▐   ▐▌  "
echo "   ▀▄▄▀   ▀▄▄▀   "
echo "        │        "
echo "  ≥≡≡  ─┴─  ≡≡≤  "
sleep 0.03
clear
echo "  ▄           ▄  "
echo " ▐█           █▌ "
echo " ▌ █         █ ▐ "
echo "▐   █       █   ▌"
echo " ▌  ▄▄     ▄▄  ▐ "
echo "   ████   ████   "
echo "  ▐████▌ ▐████▌  "
echo "  ▐████▌ ▐████▌  "
echo "   ▀██▀   ▀██▀   "
echo "        │        "
echo "  ≥≡≡  ─┴─  ≡≡≤  "
clear
echo "  ▄           ▄  "
echo " ▐█           █▌ "
echo " ▌ █         █ ▐ z"
echo "▐   █       █   ▌"
echo " ▌  ▄▄     ▄▄  ▐ "
echo "   ████   ████   "
echo "  ▐████▌ ▐████▌  "
echo "  ▐████▌ ▐████▌  "
echo "   ▀██▀   ▀██▀   "
echo "        │        "
echo "  ≥≡≡  ─┴─  ≡≡≤  "
clear
echo "  ▄           ▄  "
echo " ▐█           █▌   z"
echo " ▌ █         █ ▐ z"
echo "▐   █       █   ▌"
echo " ▌  ▄▄     ▄▄  ▐ "
echo "   ████   ████   "
echo "  ▐████▌ ▐████▌  "
echo "  ▐████▌ ▐████▌  "
echo "   ▀██▀   ▀██▀   "
echo "        │        "
echo "  ≥≡≡  ─┴─  ≡≡≤  "
clear
echo "  ▄           ▄       z"
echo " ▐█           █▌   z"
echo " ▌ █         █ ▐ z"
echo "▐   █       █   ▌"
echo " ▌  ▄▄     ▄▄  ▐ "
echo "   ████   ████   "
echo "  ▐████▌ ▐████▌  "
echo "  ▐████▌ ▐████▌  "
echo "   ▀██▀   ▀██▀   "
echo "        │        "
echo "  ≥≡≡  ─┴─  ≡≡≤  "
read -r -s -n 1
clear
echo "  ▄           ▄  "
echo " ▐█           █▌   z"
echo " ▌ █         █ ▐ z"
echo "▐   █       █   ▌"
echo " ▌  ▄▄     ▄▄  ▐ "
echo "   ████   ████   "
echo "  ▐████▌ ▐████▌  "
echo "  ▐▌   ▌ ▐   ▐▌  "
echo "   ▀▄▄▀   ▀▄▄▀   "
echo "        │        "
echo "  ≥≡≡  ─┴─  ≡≡≤  "
sleep 0.01
clear
echo "  ▄           ▄  "
echo " ▐█           █▌ "
echo " ▌ █         █ ▐ z"
echo "▐   █       █   ▌"
echo " ▌  ▄▄     ▄▄  ▐ "
echo "   ████   ████   "
echo "  ▐█▀▀▀▌ ▐▀▀▀█▌  "
echo "  ▐▌   ▌ ▐   ▐▌  "
echo "   ▀▄▄▀   ▀▄▄▀   "
echo "        │        "
echo "  ≥≡≡ └─┴─┘ ≡≡≤  "
sleep 0.01
clear
fi
echo "  ▄           ▄  "
echo " ▐█           █▌ "
echo " ▌ █         █ ▐ "
echo "▐   █       █   ▌"
echo " ▌  ▄▄     ▄▄  ▐ "
echo "   ████   ████   "
echo "  ▐█▀  ▌ ▐  ▀█▌  "
echo "  ▐▌   ▌ ▐   ▐▌  "
echo "   ▀▄▄▀   ▀▄▄▀   "
echo "        │        "
echo "  ≥≡≡ └─┴─┘ ≡≡≤  "
sleep 0.01
clear
if  (( $RANDOM %4 == 0 ))
then
echo "  ▄           ▄  "
echo " ▐█           █▌ "
echo " ▌ █         █ ▐ "
echo "▐   █       █   ▌"
echo " ▌  ▄▄     ▄▄  ▐ "
echo "   ████   ████   "
echo "  ▐████▌ ▐████▌  "
echo "  ▐▌   ▌ ▐   ▐▌  "
echo "   ▀██▀   ▀██▀   "
echo "                "
echo "  ≥≡≡  ─▲─ ≡≡≤  "
sleep .4
clear
echo "  ▄           ▄  "
echo " ▐█           █▌ "
echo " ▌ █         █ ▐ "
echo "▐   █       █   ▌"
echo " ▌  ▄▄     ▄▄  ▐ "
echo "   ████   ████   "
echo "  ▐████▌ ▐████▌  "
echo "  ▐▌   ▌ ▐   ▐▌  "
echo "   ▀██▀   ▀██▀   "
echo "       ▄▄▄       "
echo "  ≥≡≡ █████ ≡≡≤  "
sleep 1
clear
echo "  ▄           ▄  "
echo " ▐█           █▌ "
echo " ▌ █         █ ▐ "
echo "▐   █       █   ▌"
echo " ▌  ▄▄     ▄▄  ▐ "
echo "   ████   ████   "
echo "  ▐████▌ ▐████▌  "
echo "  ▐▌   ▌ ▐   ▐▌  "
echo "   ▀██▀   ▀██▀   "
echo "                "
echo "  ≥≡≡  ─▲─ ≡≡≤  "
sleep .6
clear
fi
if  (( $RANDOM %5 == 0 ))
then
echo "  ▄           ▄  "
echo " ▐█           █▌ "
echo " ▌ █         █ ▐ grum"
echo "▐   █       █   ▌"
echo " ▌  ▄▄     ▄▄  ▐ "
echo "   ████   ████   "
echo "  ▐█▀▀▀▌ ▐▀▀▀█▌  "
echo "  ▐▌   ▌ ▐   ▐▌  "
echo "   ▀▄▄▀   ▀▄▄▀   "
echo "        │        "
echo "  ≥≡≡ ──┴── ≡≡≤  "
sleep 0.01
clear
echo "                 "
echo "                 "
echo " ▌▀█         █▀▐ grumble"
echo "▐   █       █   ▌"
echo " ▌  ▄▄     ▄▄  ▐ "
echo "   ████   ████   "
echo "  ▐█▀▀▀▌ ▐▀▀▀█▌  "
echo "  ▐▌   ▌ ▐   ▐▌  "
echo "   ▀▄▄▀   ▀▄▄▀   "
echo "        │        "
echo "  ≥≡≡ ┌─┴─┐ ≡≡≤  "
sleep 0.01
clear
echo "                 "
echo "                         grumble"
echo " ▄▄▄         ▄▄▄ grumble"
echo "▐   █       █   ▌"
echo " ▌  ▄▄     ▄▄  ▐ "
echo "   ████   ████   "
echo "  ▐█▀▀▀▌ ▐▀▀▀█▌  "
echo "  ▐▌   ▌ ▐   ▐▌  "
echo "   ▀▄▄▀   ▀▄▄▀   "
echo "        │        "
echo "  ≥≡≡ ┌─┴─┐ ≡≡≤  "
read -r -s -n 1
clear
echo "                 "
echo "                 "
echo " ▌▀█         █▀▐ "
echo "▐   █       █   ▌"
echo " ▌  ▄▄     ▄▄  ▐ "
echo "   ████   ████   "
echo "  ▐█▀▀▀▌ ▐▀▀▀█▌  "
echo "  ▐▌   ▌ ▐   ▐▌  "
echo "   ▀▄▄▀   ▀▄▄▀   "
echo "        │        "
echo "  ≥≡≡ ┌─┴─┐ ≡≡≤  "
sleep 0.01
clear
echo "  ▄           ▄  "
echo " ▐█           █▌ "
echo " ▌ █         █ ▐ "
echo "▐   █       █   ▌"
echo " ▌  ▄▄     ▄▄  ▐ "
echo "   ████   ████   "
echo "  ▐█▀▀▀▌ ▐▀▀▀█▌  "
echo "  ▐▌   ▌ ▐   ▐▌  "
echo "   ▀▄▄▀   ▀▄▄▀   "
echo "        │        "
echo "  ≥≡≡ ──┴── ≡≡≤  "
sleep 0.01
clear
echo "  ▄           ▄  "
echo " ▐█           █▌ "
echo " ▌ █         █ ▐ "
echo "▐   █       █   ▌"
echo " ▌  ▄▄     ▄▄  ▐ "
echo "   ████   ████   "
echo "  ▐█▀▀▀▌ ▐▀▀▀█▌  "
echo "  ▐▌   ▌ ▐   ▐▌  "
echo "   ▀▄▄▀   ▀▄▄▀   "
echo "        │        "
echo "  ≥≡≡ └─┴─┘ ≡≡≤  "
sleep 0.01
clear
echo "  ▄           ▄  "
echo " ▐█           █▌ "
echo " ▌ █         █ ▐ "
echo "▐   █       █   ▌"
echo " ▌  ▄▄     ▄▄  ▐ "
echo "   ████   ████   "
echo "  ▐    ▌ ▐    ▌  "
echo "  ▐▌   ▌ ▐   ▐▌  "
echo "   ▀▄▄▀   ▀▄▄▀   "
echo "        │        "
echo "  ≥≡≡ └─┴─┘ ≡≡≤  "
sleep 0.05
clear
echo "  ▄           ▄  "
echo " ▐█           █▌ "
echo " ▌ █         █ ▐ "
echo "▐   █       █   ▌"
echo " ▌  ▄▄     ▄▄  ▐ "
echo "   █  █   █  █   "
echo "  ▐    ▌ ▐    ▌  "
echo "  ▐▌ ♦ ▌ ▐ ♦ ▐▌  "
echo "   ▀▄▄▀   ▀▄▄▀   "
echo "        │        "
echo "  ≥≡≡ └─┴─┘ ≡≡≤  "
echo "                 "
echo "                 "
echo "      ▄⠶⠶⠶▄     "
sleep 0.05
clear
echo "  ▄           ▄  "
echo " ▐█           █▌ "
echo " ▌ █         █ ▐ "
echo "▐   █       █   ▌"
echo " ▌  ▄▄     ▄▄  ▐ "
echo "   █  █   █  █   "
echo "  ▐    ▌ ▐    ▌  "
echo "  ▐▌ ♦ ▌ ▐ ♦ ▐▌  "
echo "   ▀▄▄▀   ▀▄▄▀   "
echo "        │        "
echo "  ≥≡≡ └─┴─┘ ≡≡≤  "
echo "                 "
echo "      ▄⠶⠶⠶▄     "
echo "       ▀▀▀       "
sleep 0.05
clear
echo "  ▄           ▄  "
echo " ▐█           █▌ "
echo " ▌ █         █ ▐  "
echo "▐   █       █   ▌"
echo " ▌  ▄▄     ▄▄  ▐ "
echo "   █  █   █  █   "
echo "  ▐    ▌ ▐    ▌  "
echo "  ▐▌ ♦ ▌ ▐ ♦ ▐▌  "
echo "   ▀▄▄▀   ▀▄▄▀   "
echo "       ▄▄▄       "
echo "  ≥≡≡ █████ ≡≡≤  "
echo "      ▄⠶⠶⠶▄     "
echo "       ▀▀▀       "
sleep 0.05
clear
echo "  ▄           ▄  "
echo " ▐█           █▌ "
echo " ▌ █         █ ▐ "
echo "▐   █       █   ▌"
echo " ▌  ▄▄     ▄▄  ▐ "
echo "   █  █   █  █   "
echo "  ▐ ♦  ▌ ▐  ♦ ▌  "
echo "  ▐▌ ♦ ▌ ▐ ♦ ▐▌  "
echo "   ▀▄▄▀   ▀▄▄▀   "
echo "       ▄▄▄       "
echo "  ≥≡≡ █████ ≡≡≤  "
echo "       ▀▀▀       "
sleep 0.05
clear
echo "  ▄           ▄  "
echo " ▐█           █▌ "
echo " ▌ █         █ ▐ "
echo "▐   █ °     █   ▌"
echo " ▌  ▄▄     ▄▄  ▐ "
echo "   █  █   █  █   "
echo "  ▐ ♦  ▌ ▐  ♦ ▌  "
echo "  ▐▌ ♦ ▌ ▐ ♦ ▐▌  "
echo "   ▀▄▄▀  °▀▄▄▀   "
echo "                 "
echo "  ≥≡≡ █████ ≡≡≤  "
sleep 0.05
clear
echo "  ▄           ▄  "
echo " ▐█           █▌ "
echo " ▌ █  °      █ ▐ "
echo "▐   █       █   ▌"
echo " ▌  ▄▄   ° ▄▄  ▐ "
echo "   █  █   █  █   "
echo "  ▐ ♦  ▌ ▐  ♦ ▌  "
echo "  ▐▌ ♦ ▌ ▐ ♦ ▐▌  "
echo "   ▀▄▄▀   ▀▄▄▀   "
echo "   °    │        "
echo "  ≥≡≡ └─┴─┘ ≡≡≤  "
sleep 0.05
clear
echo "  ▄           ▄  "
echo " ▐█       °   █▌ "
echo " ▌ █         █ ▐ "
echo "▐   █ °     █   ▌"
echo " ▌  ▄▄     ▄▄  ▐ "
echo "   █  █   █  █   "
echo "  ▐ ♦  ▌ ▐  ♦ ▌  "
echo "  ▐▌ ♦ ▌ ▐ ♦ ▐▌  "
echo "   ▀▄▄▀  °▀▄▄▀   "
echo "        │        "
echo "  ≥≡≡ └─┴─┘ ≡≡≤  "
sleep 0.05
clear
echo "  ▄           ▄  "
echo " ▐█           █▌ "
echo " ▌ █  °      █ ▐ "
echo "▐   █       █   ▌"
echo " ▌  ▄▄   ° ▄▄  ▐ "
echo "   █  █   █  █   "
echo "  ▐ ♦  ▌ ▐  ♦ ▌  "
echo "  ▐▌ ♦ ▌ ▐ ♦ ▐▌  "
echo "   ▀▄▄▀   ▀▄▄▀   "
echo "   °    │        "
echo "  ≥≡≡ └─┴─┘ ≡≡≤  "
sleep 0.05
clear
echo "  ▄           ▄  "
echo " ▐█       °   █▌ "
echo " ▌ █         █ ▐ "
echo "▐   █ °     █   ▌"
echo " ▌  ▄▄     ▄▄  ▐ "
echo "   █  █   █  █   "
echo "  ▐ ♦  ▌ ▐  ♦ ▌  "
echo "  ▐▌ ♦ ▌ ▐ ♦ ▐▌  "
echo "   ▀▄▄▀  °▀▄▄▀   "
echo "        │        "
echo "  ≥≡≡ └─┴─┘ ≡≡≤  "
sleep 0.05
clear
echo "  ▄           ▄  "
echo " ▐█           █▌ "
echo " ▌ █  °      █ ▐ "
echo "▐   █       █   ▌"
echo " ▌  ▄▄   ° ▄▄  ▐ "
echo "   █  █   █  █   "
echo "  ▐ ♦  ▌ ▐  ♦ ▌  "
echo "  ▐▌ ♦ ▌ ▐ ♦ ▐▌  "
echo "   ▀▄▄▀   ▀▄▄▀   "
echo "   °    │        "
echo "  ≥≡≡ └─┴─┘ ≡≡≤  "
sleep 0.05
clear
echo "  ▄           ▄  "
echo " ▐█       °   █▌ "
echo " ▌ █         █ ▐ "
echo "▐   █ °     █   ▌"
echo " ▌  ▄▄     ▄▄  ▐ "
echo "   █  █   █  █   "
echo "  ▐ ♦  ▌ ▐  ♦ ▌  "
echo "  ▐▌ ♦ ▌ ▐ ♦ ▐▌  "
echo "   ▀▄▄▀  °▀▄▄▀   "
echo "        │        "
echo "  ≥≡≡ └─┴─┘ ≡≡≤  "
sleep 0.05
clear
echo "  ▄           ▄  "
echo " ▐█           █▌ "
echo " ▌ █         █ ▐ "
echo "▐   █       █   ▌"
echo " ▌  ▄▄     ▄▄  ▐ "
echo "   ████   ████   "
echo "  ▐    ▌ ▐    ▌  "
echo "  ▐▌   ▌ ▐   ▐▌  "
echo "   ▀▄▄▀   ▀▄▄▀   "
echo "        │        "
echo "  ≥≡≡ └─┴─┘ ≡≡≤  "
sleep 0.05
clear
fi
done
